apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-deploy
spec:
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
      - name: docs
        image: agatalba/tfm-mca-filemanagement-docs:1.0.18
        env:
          - name: DOCS_PATH
            value: /tmp/docs
          - name: DB_HOST
            value: mysql-service
          - name: DB_USER
            value: root
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: files-secrets
                key: mysqlpass
          - name: KAFKA_HOST
            value: kafka-service
          - name: KAFKA_PORT
            value: "29092"
          - name: ZOOKEEPER_HOST
            value: zookeeper
          - name: ZOOKEEPER_PORT
            value: "2181"
        ports:
          - containerPort: 8083
        volumeMounts:
          - mountPath: /tmp/docs
            name: docs-claim
      volumes:
        - name: docs-claim
          persistentVolumeClaim:
            claimName: docs-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: docs-pv
spec:
  storageClassName: standar-rwo
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Mi  
  hostPath:
    path: /host/docs                
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docs-claim
spec:
  storageClassName: standar-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: docs-service
spec:
  type: ClusterIP
  selector:
    app: docs
  ports:
  - name: docs-port
    port: 8083
