apiVersion: apps/v1
kind: Deployment
metadata:
  name: files-deploy
spec:
  selector:
    matchLabels:
      app: files
  template:
    metadata:
      labels:
        app: files
    spec:
      containers:
      - name: files
        image: agatalba/tfm-mca-filemanagement-files:1.0.6
        imagePullPolicy: Always
        env:
          - name: DB_HOST
            value: mysql-service
          - name: DB_USER
            value: root
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: files-secrets
                key: mysqlpass
          - name: KAFKA_HOST
            value: kafka-service
          - name: KAFKA_PORT
            value: "29092"
          - name: ZOOKEEPER_HOST
            value: zookeeper
          - name: ZOOKEEPER_PORT
            value: "2181"
          - name: USERS_HOST
            value: oauth2
          - name: USERS_PORT
            value: "8081"
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: files-service
spec:
  type: ClusterIP
  selector:
    app: files
  ports:
  - name: files-port
    port: 8080
