apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploy
  namespace: tfm-pre-agat-prog
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: agatalba/tfm-mca-filemanagement-gateway:0.0.1
        env:
          - name: FILES_HOST
            value: files-service       
          - name: FILES_PORT
            value: "8080"
          - name: USERS_HOST
            value: oauth2
          - name: USERS_PORT 
            value: "8081"
          - name: BPM_HOST 
            value: bpm-service
          - name: BPM_PORT 
            value: "8082"
          - name: DOCS_HOST 
            value: docs-service
          - name: DOCS_PORT 
            value: "8083"
          - name: INDEX_HOST 
            value: index-service
          - name: INDEX_PORT 
            value: "8084"          
        ports:
          - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: tfm-pre-agat-prog
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
  - name: gateway-port
    port: 8085