apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2
spec:
  selector:
    matchLabels:
      app: oauth2
  template:
    metadata:
      labels:
        app: oauth2
    spec:
      containers:
      - name: oauth2
        image: agatalba/tfm-mca-filemanagement-oauth2:1.0.11-SNAPSHOT
        env:
        - name: DB_HOST
          value: mysql-service
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: files-secrets
              key: mysqlpass
        ports:
          - containerPort: 8081
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2
spec:
  type: ClusterIP
  selector:
    app: oauth2
  ports:
  - name: oauth2-port
    port: 8081