---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-deploy
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: "mongodb-service" 
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:5.0.6-focal
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-claim
      restartPolicy: Always
      volumes:
        - name: mongodb-claim
          persistentVolumeClaim:
            claimName: mongodb-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb-port
  selector:
    app: mongodb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  storageClassName: standar-rwo
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi  
  hostPath:
    path: /host/mongodb    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongodb-claim
  name: mongodb-claim
spec:
  storageClassName: standar-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi