apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-deploy
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"      
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: eventuateio/eventuate-tram-sagas-mysql:0.18.0.RELEASE
          args:
              - "--ignore-db-dir=lost+found"          
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: files-secrets
                  key: mysqlpass
            - name: MYSQL_USER
              value: mysqluser
            - name: MYSQL_PASSWORD
              value: mysqlpw
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-claim
      volumes:
        - name: mysql-claim
          persistentVolumeClaim:
            claimName: mysql-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql-port
  selector:
    app: mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  storageClassName: standar-rwo
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi  
  hostPath:
    path: /host/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-claim
spec:
  storageClassName: standar-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi