apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    name: zookeeper
  annotations:
    dev.okteto.com/auto-ingress: 'false'
spec:
  ports:
  - port: 2181
    targetPort: 2181
    protocol: TCP
    name: zookeeper-port
  selector:
    app: zookeeper
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  serviceName: "zookeeper"
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:5.2.4
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
          volumeMounts:
            - name: zookeeper-claim
              mountPath: /var/lib/zookeeper/data
      volumes:
        - name: zookeeper-claim
          persistentVolumeClaim:
            claimName: zookeeper-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper-claim
  name: zookeeper-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
