apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-data-pvclaim
spec:
  storageClassName: standar-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-certs-pvclaim
spec:
  storageClassName: standar-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-docker-sock-pvclaim
spec:
  storageClassName: standar-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi